---
- hosts: all
  become: yes
  tasks:
    - name: Détecter la distribution
      command: cat /etc/os-release
      register: os_release

    - name: Afficher les informations de la distribution
      debug:
        msg: "{{ os_release.stdout }}"

    - name: Créer l'utilisateur mon_user sur Debian/Ubuntu
      command: useradd -m -s /bin/bash mon_user
      when: "'ID=ubuntu' in os_release.stdout or 'ID=debian' in os_release.stdout"

    - name: Créer l'utilisateur mon_user sur Amazon Linux
      command: useradd -m -s /bin/bash mon_user
      when: "'ID=\"amzn\"' in os_release.stdout"

    - name: Créer l'utilisateur mon_user sur CentOS/RHEL
      command: useradd -m -s /bin/bash mon_user
      when: "'ID=centos' in os_release.stdout or 'ID=rhel' in os_release.stdout"

    - name: Ajouter l'utilisateur mon_user au groupe docker
      command: usermod -aG docker mon_user
