name: Deploy to Server

on:
  push:
    branches:
      - main  # Déclencher le workflow sur les commits poussés vers la branche "main"
      - dev   # Déclencher le workflow sur les commits poussés vers la branche "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg-agent \
          software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory deploy.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "false"
